# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DataPush' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DataPush

  pod ‘Firebase’
  pod ‘Firebase/Messaging’

  target 'DataPushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataPushUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
